server {
    listen 80;
    listen [::]:80;
    server_name dokin-app.online www.dokin-app.online test1.dokin-app.ru test3.dokin-app.ru 5.39.220.96 5.39.220.96.sslip.io;

    access_log /var/log/nginx/competitions.access.log;
    error_log /var/log/nginx/competitions.error.log;

    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }
}
